---
title: "I am Jimena Golcher-Benavides."
output: 
  html_document:
    css: ['CSSBackgrounds.css', 'CSSFonts.css']
    includes:
      after_body: footer.html
---

 I’m currently a postdoctoral researcher in the Department of Natural Resource Ecology and Management at Iowa State University. I joined [Dr. Michael J. Weber](https://michaeljohnweber.wixsite.com/fisherieslab)'s & USGS Iowa Cooperative Fish and Wildlife Research Unit leader [Dr. Michael J. Moore](https://moorefishlab.weebly.com/)'s labs. For my 1st year of postdoctoral research I investigated recruitment patterns of bigheaded carps invading the Mississippi River Basin. Currently, I am building upon this research by delving into the temporal dynamics of introgression between the two bigheaded carps using reduced-representation RAD-sequencing data. 
 
 Last year, I concluded a 1-year Visiting Assistant Professor at [Lees-McRae College](https://www.lmc.edu). In 2021, I graduated from the interdisciplinary [Program in Ecology](http://www.uwyo.edu/pie/) as part of Dr. Catherine E. Wagner's Lab at University of Wyoming, Laramie WY. For my PhD, I studied drivers of cichlid fish diversity in shallow environments in the littoral of Lake Tanganyika, East Africa, combining population genomic technologies, biodiversity surveys, behavioral assays, and natural history observations. Such an integrative approach provided a unique glimpse into both the origination and persistence processes underlying endemic ichthyofaunal diversity accumulation. I pursued a scientific career thanks to support from Dr. Maurizzio Protti Quesada at Universidad Nacional UNA, in Costa Rica who first exposed me to tropical freshwater ichthyology. I studied abroad thanks to an academic exchange program through UNA and the german gouvernment agency DAAD at TiHo Hannover, as well as a graduate studies fellowship from the Costa Rican government scientific funding agency CONICIT to do my master's in biology at University of Konstanz in Germany.

 
  I have always loved learning languages, culture, and history, and more recently contributing to [iNaturalist](https://www.inaturalist.org/users/318056). I value most being outside or underwater, as well as quality time with friends and family.


